import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/shared/app-sidebar";
import { getSidebarMenuItemsAPI } from "@/app/api";
import DashboardNavBar from "@/components/navigation/DashboardNavBar";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "C Tech Learn Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sidebarMenuItemData = await getSidebarMenuItemsAPI();

  return (
    <html lang="en">
      <body className={`${montserrat.variable} custom-scrollbar dark:bg-primary bg-white dark:text-white text-primary`}>
        <SidebarProvider>
          <AppSidebar sidebarMenuItemData={sidebarMenuItemData} />
          <main className="w-full">
            <DashboardNavBar />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
